package tobii.lowlevel.sdk;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This struct holds a three dimensional point.<br>
 * @field x X coordinate.<br>
 * @field y Y coordinate.<br>
 * @field z Z coordinate.<br>
 * <i>native declaration : tobii_gaze_sdk/include/tobiigaze_data_types.h:278</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("TobiiGazeCore64") 
public class tobiigaze_point_3d extends StructObject {
	@Field(0) 
	public double x() {
		return this.io.getDoubleField(this, 0);
	}
	@Field(0) 
	public tobiigaze_point_3d x(double x) {
		this.io.setDoubleField(this, 0, x);
		return this;
	}
	@Field(1) 
	public double y() {
		return this.io.getDoubleField(this, 1);
	}
	@Field(1) 
	public tobiigaze_point_3d y(double y) {
		this.io.setDoubleField(this, 1, y);
		return this;
	}
	@Field(2) 
	public double z() {
		return this.io.getDoubleField(this, 2);
	}
	@Field(2) 
	public tobiigaze_point_3d z(double z) {
		this.io.setDoubleField(this, 2, z);
		return this;
	}
	public tobiigaze_point_3d() {
		super();
	}
	public tobiigaze_point_3d(Pointer pointer) {
		super(pointer);
	}
}
