package tobii.lowlevel.sdk;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : tobii_gaze_sdk/include/tobiigaze_data_types.h:543</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("TobiiGazeCore64") 
public class tobiigaze_pay_per_use_info extends StructObject {
	@Field(0) 
	public int is_ppu_unit() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public tobiigaze_pay_per_use_info is_ppu_unit(int is_ppu_unit) {
		this.io.setIntField(this, 0, is_ppu_unit);
		return this;
	}
	@Field(1) 
	public int realm_id() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public tobiigaze_pay_per_use_info realm_id(int realm_id) {
		this.io.setIntField(this, 1, realm_id);
		return this;
	}
	@Field(2) 
	public int realm_is_authorized() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public tobiigaze_pay_per_use_info realm_is_authorized(int realm_is_authorized) {
		this.io.setIntField(this, 2, realm_is_authorized);
		return this;
	}
	public tobiigaze_pay_per_use_info() {
		super();
	}
	public tobiigaze_pay_per_use_info(Pointer pointer) {
		super(pointer);
	}
}
