package tobii.lowlevel.sdk;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : tobii_gaze_sdk/include/tobiigaze_data_types.h:532</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("TobiiGazeCore64") 
public class tobiigaze_geometry_mounting extends StructObject {
	@Field(0) 
	public int guides() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public tobiigaze_geometry_mounting guides(int guides) {
		this.io.setIntField(this, 0, guides);
		return this;
	}
	@Field(1) 
	public float width() {
		return this.io.getFloatField(this, 1);
	}
	@Field(1) 
	public tobiigaze_geometry_mounting width(float width) {
		this.io.setFloatField(this, 1, width);
		return this;
	}
	@Field(2) 
	public float angle() {
		return this.io.getFloatField(this, 2);
	}
	@Field(2) 
	public tobiigaze_geometry_mounting angle(float angle) {
		this.io.setFloatField(this, 2, angle);
		return this;
	}
	/// C type : tobiigaze_point_3d
	@Field(3) 
	public tobiigaze_point_3d external_offset() {
		return this.io.getNativeObjectField(this, 3);
	}
	/// C type : tobiigaze_point_3d
	@Field(3) 
	public tobiigaze_geometry_mounting external_offset(tobiigaze_point_3d external_offset) {
		this.io.setNativeObjectField(this, 3, external_offset);
		return this;
	}
	/// C type : tobiigaze_point_3d
	@Field(4) 
	public tobiigaze_point_3d internal_offset() {
		return this.io.getNativeObjectField(this, 4);
	}
	/// C type : tobiigaze_point_3d
	@Field(4) 
	public tobiigaze_geometry_mounting internal_offset(tobiigaze_point_3d internal_offset) {
		this.io.setNativeObjectField(this, 4, internal_offset);
		return this;
	}
	public tobiigaze_geometry_mounting() {
		super();
	}
	public tobiigaze_geometry_mounting(Pointer pointer) {
		super(pointer);
	}
}
