package tobii.lowlevel.sdk;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This structs holds the units given name.<br>
 * <i>native declaration : tobii_gaze_sdk/include/tobiigaze_data_types.h:495</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("TobiiGazeCore64") 
public class tobiigaze_unit_name extends StructObject {
	/// C type : char[TOBIIGAZE_UNIT_NAME_MAX_SIZE]
	@Array({64}) 
	@Field(0) 
	public Pointer<Byte > data() {
		return this.io.getPointerField(this, 0);
	}
	public tobiigaze_unit_name() {
		super();
	}
	public tobiigaze_unit_name(Pointer pointer) {
		super(pointer);
	}
}
