package tobii.lowlevel.sdk;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This struct holds a gaze data extension.<br>
 * @field column_id The id of the extension which uniquely identifies it.<br>
 * @field data The extension data. Use the helper functions in tobiigaze_ext.h to convert this data to types.<br>
 * @field actual_size The size of the data.<br>
 * <i>native declaration : tobii_gaze_sdk/include/tobiigaze_data_types.h:355</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("TobiiGazeCore64") 
public class tobiigaze_gaze_data_extension extends StructObject {
	@Field(0) 
	public int column_id() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public tobiigaze_gaze_data_extension column_id(int column_id) {
		this.io.setIntField(this, 0, column_id);
		return this;
	}
	/// C type : uint8_t[TOBIIGAZE_MAX_GAZE_DATA_EXTENSION_LENGTH]
	@Array({256}) 
	@Field(1) 
	public Pointer<Byte > data() {
		return this.io.getPointerField(this, 1);
	}
	@Field(2) 
	public int actual_size() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public tobiigaze_gaze_data_extension actual_size(int actual_size) {
		this.io.setIntField(this, 2, actual_size);
		return this;
	}
	public tobiigaze_gaze_data_extension() {
		super();
	}
	public tobiigaze_gaze_data_extension(Pointer pointer) {
		super(pointer);
	}
}
