package tobii.lowlevel.sdk;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : tobii_gaze_sdk/include/tobiigaze_data_types.h:525</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("TobiiGazeCore64") 
public class tobiigaze_wake_on_gaze_configuration extends StructObject {
	/// milliseconds
	@Field(0) 
	public int dwell_time() {
		return this.io.getIntField(this, 0);
	}
	/// milliseconds
	@Field(0) 
	public tobiigaze_wake_on_gaze_configuration dwell_time(int dwell_time) {
		this.io.setIntField(this, 0, dwell_time);
		return this;
	}
	/// C type : tobiigaze_wake_on_gaze_region[TOBIIGAZE_MAX_WAKE_ON_GAZE_REGIONS]
	@Array({4}) 
	@Field(1) 
	public Pointer<tobiigaze_wake_on_gaze_region > region() {
		return this.io.getPointerField(this, 1);
	}
	@Field(2) 
	public int actual_size() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public tobiigaze_wake_on_gaze_configuration actual_size(int actual_size) {
		this.io.setIntField(this, 2, actual_size);
		return this;
	}
	public tobiigaze_wake_on_gaze_configuration() {
		super();
	}
	public tobiigaze_wake_on_gaze_configuration(Pointer pointer) {
		super(pointer);
	}
}
