package tobii.lowlevel.sdk;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This struct holds a rectangle.<br>
 * @field left Specifies the x-coordinate of the upper-left corner of a rectangle.<br>
 * @field top Specifies the y-coordinate of the upper-left corner of a rectangle.<br>
 * @field right Specifies the x-coordinate of the lower-right corner of a rectangle.<br>
 * @field bottom Specifies the y-coordinate of the lower-right corner of a rectangle.<br>
 * <i>native declaration : tobii_gaze_sdk\include\tobiigaze_data_types.h:182</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("TobiiGazeCore64") 
public class tobiigaze_rect extends StructObject {
	@Field(0) 
	public int left() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public tobiigaze_rect left(int left) {
		this.io.setIntField(this, 0, left);
		return this;
	}
	@Field(1) 
	public int top() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public tobiigaze_rect top(int top) {
		this.io.setIntField(this, 1, top);
		return this;
	}
	@Field(2) 
	public int right() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public tobiigaze_rect right(int right) {
		this.io.setIntField(this, 2, right);
		return this;
	}
	@Field(3) 
	public int bottom() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public tobiigaze_rect bottom(int bottom) {
		this.io.setIntField(this, 3, bottom);
		return this;
	}
	public tobiigaze_rect() {
		super();
	}
	public tobiigaze_rect(Pointer pointer) {
		super(pointer);
	}
}
