package tobii.lowlevel.sdk;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This struct holds gaze data for one eye.<br>
 * @field eye_position_from_eye_tracker_mm<br>
 * @field eye_position_in_track_box_normalized<br>
 * @field gaze_point_from_eye_tracker_mm<br>
 * @field gaze_point_on_display_normalized<br>
 * <i>native declaration : tobii_gaze_sdk\include\tobiigaze_data_types.h:202</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("TobiiGazeCore") 
public class tobiigaze_gaze_data_eye extends StructObject {
	/// C type : tobiigaze_point_3d
	@Field(0) 
	public tobiigaze_point_3d eye_position_from_eye_tracker_mm() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : tobiigaze_point_3d
	@Field(0) 
	public tobiigaze_gaze_data_eye eye_position_from_eye_tracker_mm(tobiigaze_point_3d eye_position_from_eye_tracker_mm) {
		this.io.setNativeObjectField(this, 0, eye_position_from_eye_tracker_mm);
		return this;
	}
	/// C type : tobiigaze_point_3d
	@Field(1) 
	public tobiigaze_point_3d eye_position_in_track_box_normalized() {
		return this.io.getNativeObjectField(this, 1);
	}
	/// C type : tobiigaze_point_3d
	@Field(1) 
	public tobiigaze_gaze_data_eye eye_position_in_track_box_normalized(tobiigaze_point_3d eye_position_in_track_box_normalized) {
		this.io.setNativeObjectField(this, 1, eye_position_in_track_box_normalized);
		return this;
	}
	/// C type : tobiigaze_point_3d
	@Field(2) 
	public tobiigaze_point_3d gaze_point_from_eye_tracker_mm() {
		return this.io.getNativeObjectField(this, 2);
	}
	/// C type : tobiigaze_point_3d
	@Field(2) 
	public tobiigaze_gaze_data_eye gaze_point_from_eye_tracker_mm(tobiigaze_point_3d gaze_point_from_eye_tracker_mm) {
		this.io.setNativeObjectField(this, 2, gaze_point_from_eye_tracker_mm);
		return this;
	}
	/// C type : tobiigaze_point_2d
	@Field(3) 
	public tobiigaze_point_2d gaze_point_on_display_normalized() {
		return this.io.getNativeObjectField(this, 3);
	}
	/// C type : tobiigaze_point_2d
	@Field(3) 
	public tobiigaze_gaze_data_eye gaze_point_on_display_normalized(tobiigaze_point_2d gaze_point_on_display_normalized) {
		this.io.setNativeObjectField(this, 3, gaze_point_on_display_normalized);
		return this;
	}
	public tobiigaze_gaze_data_eye() {
		super();
	}
	public tobiigaze_gaze_data_eye(Pointer pointer) {
		super(pointer);
	}
}
