package tobii.lowlevel.sdk;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * Contains an illumination mode identifier.<br>
 * <i>native declaration : tobii_gaze_sdk/include/tobiigaze_data_types.h:471</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("TobiiGazeCore64") 
public class tobiigaze_illumination_mode extends StructObject {
	/// C type : char[TOBIIGAZE_ILLUMINATION_MODE_STRING_MAX_SIZE]
	@Array({64}) 
	@Field(0) 
	public Pointer<Byte > data() {
		return this.io.getPointerField(this, 0);
	}
	public tobiigaze_illumination_mode() {
		super();
	}
	public tobiigaze_illumination_mode(Pointer pointer) {
		super(pointer);
	}
}
