package tobii.lowlevel.sdk;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This struct holds a track box<br>
 * @field front_upper_right_point <br>
 * @field front_upper_left_point  <br>
 * @field front_lower_left_point  <br>
 * @field front_lower_right_point <br>
 * @field back_upper_right_point  <br>
 * @field back_upper_left_point  <br>
 * @field back_lower_left_point  <br>
 * @field back_lower_right_point<br>
 * <i>native declaration : tobii_gaze_sdk\include\tobiigaze_data_types.h:254</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("TobiiGazeCore64") 
public class tobiigaze_track_box extends StructObject {
	/// C type : tobiigaze_point_3d
	@Field(0) 
	public tobiigaze_point_3d front_upper_right_point() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : tobiigaze_point_3d
	@Field(0) 
	public tobiigaze_track_box front_upper_right_point(tobiigaze_point_3d front_upper_right_point) {
		this.io.setNativeObjectField(this, 0, front_upper_right_point);
		return this;
	}
	/// C type : tobiigaze_point_3d
	@Field(1) 
	public tobiigaze_point_3d front_upper_left_point() {
		return this.io.getNativeObjectField(this, 1);
	}
	/// C type : tobiigaze_point_3d
	@Field(1) 
	public tobiigaze_track_box front_upper_left_point(tobiigaze_point_3d front_upper_left_point) {
		this.io.setNativeObjectField(this, 1, front_upper_left_point);
		return this;
	}
	/// C type : tobiigaze_point_3d
	@Field(2) 
	public tobiigaze_point_3d front_lower_left_point() {
		return this.io.getNativeObjectField(this, 2);
	}
	/// C type : tobiigaze_point_3d
	@Field(2) 
	public tobiigaze_track_box front_lower_left_point(tobiigaze_point_3d front_lower_left_point) {
		this.io.setNativeObjectField(this, 2, front_lower_left_point);
		return this;
	}
	/// C type : tobiigaze_point_3d
	@Field(3) 
	public tobiigaze_point_3d front_lower_right_point() {
		return this.io.getNativeObjectField(this, 3);
	}
	/// C type : tobiigaze_point_3d
	@Field(3) 
	public tobiigaze_track_box front_lower_right_point(tobiigaze_point_3d front_lower_right_point) {
		this.io.setNativeObjectField(this, 3, front_lower_right_point);
		return this;
	}
	/// C type : tobiigaze_point_3d
	@Field(4) 
	public tobiigaze_point_3d back_upper_right_point() {
		return this.io.getNativeObjectField(this, 4);
	}
	/// C type : tobiigaze_point_3d
	@Field(4) 
	public tobiigaze_track_box back_upper_right_point(tobiigaze_point_3d back_upper_right_point) {
		this.io.setNativeObjectField(this, 4, back_upper_right_point);
		return this;
	}
	/// C type : tobiigaze_point_3d
	@Field(5) 
	public tobiigaze_point_3d back_upper_left_point() {
		return this.io.getNativeObjectField(this, 5);
	}
	/// C type : tobiigaze_point_3d
	@Field(5) 
	public tobiigaze_track_box back_upper_left_point(tobiigaze_point_3d back_upper_left_point) {
		this.io.setNativeObjectField(this, 5, back_upper_left_point);
		return this;
	}
	/// C type : tobiigaze_point_3d
	@Field(6) 
	public tobiigaze_point_3d back_lower_left_point() {
		return this.io.getNativeObjectField(this, 6);
	}
	/// C type : tobiigaze_point_3d
	@Field(6) 
	public tobiigaze_track_box back_lower_left_point(tobiigaze_point_3d back_lower_left_point) {
		this.io.setNativeObjectField(this, 6, back_lower_left_point);
		return this;
	}
	/// C type : tobiigaze_point_3d
	@Field(7) 
	public tobiigaze_point_3d back_lower_right_point() {
		return this.io.getNativeObjectField(this, 7);
	}
	/// C type : tobiigaze_point_3d
	@Field(7) 
	public tobiigaze_track_box back_lower_right_point(tobiigaze_point_3d back_lower_right_point) {
		this.io.setNativeObjectField(this, 7, back_lower_right_point);
		return this;
	}
	public tobiigaze_track_box() {
		super();
	}
	public tobiigaze_track_box(Pointer pointer) {
		super(pointer);
	}
}
