package tobii.lowlevel.sdk;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This structs contains data for sending and receiving custom commands. @field data<br>
 * must be allocated by the client.<br>
 * <i>native declaration : tobii_gaze_sdk/include/tobiigaze_data_types.h:490</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("TobiiGazeCore64") 
public class tobiigaze_custom_command extends StructObject {
	/// C type : uint8_t*
	@Field(0) 
	public Pointer<Byte > data() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : uint8_t*
	@Field(0) 
	public tobiigaze_custom_command data(Pointer<Byte > data) {
		this.io.setPointerField(this, 0, data);
		return this;
	}
	@Field(1) 
	public int capacity() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public tobiigaze_custom_command capacity(int capacity) {
		this.io.setIntField(this, 1, capacity);
		return this;
	}
	@Field(2) 
	public int actual_size() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public tobiigaze_custom_command actual_size(int actual_size) {
		this.io.setIntField(this, 2, actual_size);
		return this;
	}
	public tobiigaze_custom_command() {
		super();
	}
	public tobiigaze_custom_command(Pointer pointer) {
		super(pointer);
	}
}
