package tobii.lowlevel.sdk;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This struct holds a list of extensions.<br>
 * <i>native declaration : tobii_gaze_sdk/include/tobiigaze_data_types.h:515</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("TobiiGazeCore64") 
public class tobiigaze_extensions extends StructObject {
	/// C type : tobiigaze_extension[TOBIIGAZE_EXTENSIONS_MAX_SIZE]
	@Array({16}) 
	@Field(0) 
	public Pointer<tobiigaze_extension > extensions() {
		return this.io.getPointerField(this, 0);
	}
	@Field(1) 
	public int actual_size() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public tobiigaze_extensions actual_size(int actual_size) {
		this.io.setIntField(this, 1, actual_size);
		return this;
	}
	public tobiigaze_extensions() {
		super();
	}
	public tobiigaze_extensions(Pointer pointer) {
		super(pointer);
	}
}
