package tobii.lowlevel.sdk;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : tobii_gaze_sdk/include/tobiigaze_data_types.h:519</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("TobiiGazeCore64") 
public class tobiigaze_wake_on_gaze_region extends StructObject {
	/// C type : tobiigaze_point_2d
	@Field(0) 
	public tobiigaze_point_2d upper_left() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : tobiigaze_point_2d
	@Field(0) 
	public tobiigaze_wake_on_gaze_region upper_left(tobiigaze_point_2d upper_left) {
		this.io.setNativeObjectField(this, 0, upper_left);
		return this;
	}
	/// C type : tobiigaze_point_2d
	@Field(1) 
	public tobiigaze_point_2d lower_right() {
		return this.io.getNativeObjectField(this, 1);
	}
	/// C type : tobiigaze_point_2d
	@Field(1) 
	public tobiigaze_wake_on_gaze_region lower_right(tobiigaze_point_2d lower_right) {
		this.io.setNativeObjectField(this, 1, lower_right);
		return this;
	}
	public tobiigaze_wake_on_gaze_region() {
		super();
	}
	public tobiigaze_wake_on_gaze_region(Pointer pointer) {
		super(pointer);
	}
}
