package tobii.lowlevel.sdk;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This struct holds timesync information.<br>
 * <i>native declaration : tobii_gaze_sdk/include/tobiigaze_data_types.h:549</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("TobiiGazeCore64") 
public class tobiigaze_timesync_info extends StructObject {
	@Field(0) 
	public int packet_number() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public tobiigaze_timesync_info packet_number(int packet_number) {
		this.io.setIntField(this, 0, packet_number);
		return this;
	}
	@Field(1) 
	public long remote_timestamp() {
		return this.io.getLongField(this, 1);
	}
	@Field(1) 
	public tobiigaze_timesync_info remote_timestamp(long remote_timestamp) {
		this.io.setLongField(this, 1, remote_timestamp);
		return this;
	}
	public tobiigaze_timesync_info() {
		super();
	}
	public tobiigaze_timesync_info(Pointer pointer) {
		super(pointer);
	}
}
