package tobii.lowlevel.sdk;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : tobii_gaze_sdk\include\tobiigaze_data_types.h:288</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("TobiiGazeCore") 
public class usb_device_info extends StructObject {
	/// C type : char[TOBII_USB_DEVICE_INFO_MAX_SIZE]
	@Array({128}) 
	@Field(0) 
	public Pointer<Byte > serialNumber() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : char[TOBII_USB_DEVICE_INFO_MAX_SIZE]
	@Array({128}) 
	@Field(1) 
	public Pointer<Byte > productName() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : char[TOBII_USB_DEVICE_INFO_MAX_SIZE]
	@Array({128}) 
	@Field(2) 
	public Pointer<Byte > platformType() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : char[TOBII_USB_DEVICE_INFO_MAX_SIZE]
	@Array({128}) 
	@Field(3) 
	public Pointer<Byte > firmwareVersion() {
		return this.io.getPointerField(this, 3);
	}
	public usb_device_info() {
		super();
	}
	public usb_device_info(Pointer pointer) {
		super(pointer);
	}
}
